spring.application.name=vikpix-api
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vikpix}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:vikpix}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vikpix}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false

server.error.include-stacktrace=never
server.error.include-message=always



spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/vikpix}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/vikpix/protocol/openid-connect/certs}

keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8081}
keycloak.public-auth-server-url=${KEYCLOAK_PUBLIC_AUTH_SERVER_URL:http://localhost:8081}
keycloak.realm=${KEYCLOAK_REALM:vikpix}
keycloak.admin-client-id=${KEYCLOAK_ADMIN_CLIENT_ID:vikpix-api}
keycloak.admin-client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

app.mail.from-email=${MAIL_FROM_EMAIL}
app.mail.from-name=${MAIL_FROM_NAME:VikPix}

app.frontend-url=${VIKPIX_WEB_ORIGIN:http://localhost:5173}
app.backend-url=${APP_BACKEND_URL:http://localhost:8080}
app.security.encryption-key=dev-only-change-this-32-byte-secret

mercadopago.access-token=${MERCADO_PAGO_ACCESS_TOKEN:}
mercadopago.notification-url=${MERCADO_PAGO_NOTIFICATION_URL:http://localhost:8080/api/payments/mercadopago/webhook}
mercadopago.webhook-secret=${MERCADO_PAGO_WEBHOOK_SECRET:}
app.cors.allowed-origins=${VIKPIX_WEB_ORIGIN:http://localhost:5173}
